build.gradle
src/main/generated/com/example/meettify/entity/jwt/QTokenEntity.java
src/main/java/com/example/meettify/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/meettify/config/jwt/JwtProvider.java
src/main/java/com/example/meettify/config/jwt/JwtSecurityConfig.java
src/main/java/com/example/meettify/dto/jwt/TokenDTO.java
src/main/java/com/example/meettify/entity/jwt/TokenEntity.java

close #6 
jwt 12 버전으로 jwt 기능 구현

[Feat] JWT 기능 구현

---

src/main/java/com/example/meettify/exception/GlobalExceptionAdvice.java
src/main/java/com/example/meettify/exception/board/BoardException.java
src/main/java/com/example/meettify/exception/cart/CartException.java
src/main/java/com/example/meettify/exception/comment/CommentException.java
src/main/java/com/example/meettify/exception/externalService/ExternalServiceException.java
src/main/java/com/example/meettify/exception/file/FileDownloadException.java
src/main/java/com/example/meettify/exception/file/FileUploadException.java
src/main/java/com/example/meettify/exception/item/ItemException.java
src/main/java/com/example/meettify/exception/jwt/JwtAccessDeniedHandler.java
src/main/java/com/example/meettify/exception/jwt/JwtAccessHandler.java
src/main/java/com/example/meettify/exception/jwt/JwtAuthenticationEntryPoint.java
src/main/java/com/example/meettify/exception/member/MemberException.java
src/main/java/com/example/meettify/exception/order/OrderException.java
src/main/java/com/example/meettify/exception/sessionExpire/SessionExpiredException.java
src/main/java/com/example/meettify/exception/stock/OutOfStockException.java
src/main/java/com/example/meettify/exception/validation/DataValidationException.java

[Feat] exception 기능 구현

---

src/main/java/com/example/meettify/controller/member/MemberController.java
src/main/java/com/example/meettify/dto/member/LoginDTO.java
src/main/java/com/example/meettify/repository/jwt/TokenRepository.java
src/main/java/com/example/meettify/service/member/MemberService.java
src/main/java/com/example/meettify/service/member/MemberServiceImpl.java

[Feat] login 기능 구현

---

.github/workflows/action.yml
build.gradle
docker/Dockerfile
docker/docker-compose.yml

[Add] git action & docker

---

src/main/java/com/example/meettify/controller/member/MemberController.java
src/main/java/com/example/meettify/service/member/MemberService.java
src/main/java/com/example/meettify/service/member/MemberServiceImpl.java

[Feat] 회원탈퇴 기능 구현

---

.github/workflows/action.yml

CI/CD 에서 docker-compose도 설치할 수 있도록 수정

[Modify] action.yml 수정

---

src/main/java/com/example/meettify/dto/meet/MeetServiceDTO.java
src/main/java/com/example/meettify/dto/meet/RequestMeetDTO.java
src/main/java/com/example/meettify/dto/meet/ResponseMeetDTO.java
src/main/java/com/example/meettify/dto/meet/category/Category.java
src/main/java/com/example/meettify/entity/Category.java
src/main/java/com/example/meettify/entity/Meet/MeetBoardEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetBoardImageEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetImageEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetMemberEntity.java

모임 엔티티와 DTO를 구성하였음. 
close #41

[Feat] 모임 엔티티 구성하기

---

src/main/java/com/example/meettify/controller/member/MemberController.java
src/main/java/com/example/meettify/entity/Meet/MeetBoardEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetBoardImageEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetImageEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetMemberEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetRole.java
src/main/java/com/example/meettify/repository/meet/MeetImageRepository.java
src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java

[Fix] 모임 권한 관련 클래스 추가

---

.github/workflows/action.yml
.gitignore
src/main/java/com/example/meettify/config/oauth/GoogleUser.java
src/main/java/com/example/meettify/config/oauth/NaverUser.java
src/main/java/com/example/meettify/config/oauth/OAuth2FailHandler.java
src/main/java/com/example/meettify/config/oauth/OAuth2SuccessHandler.java
src/main/java/com/example/meettify/config/oauth/OAuthProviderUser.java
src/main/java/com/example/meettify/config/oauth/OAuthUserInfo.java
src/main/java/com/example/meettify/config/oauth/PrincipalOAuthUserService.java
src/main/java/com/example/meettify/config/security/PrincipalDetails.java
src/main/java/com/example/meettify/config/security/PrincipalDetailsService.java
src/main/java/com/example/meettify/config/security/SecurityConfig.java
src/main/java/com/example/meettify/dto/member/SocialDTO.java
src/main/java/com/example/meettify/entity/member/MemberEntity.java

[Feat] OAuth2.0 로그인 기능 구현

---

.github/workflows/action.yml
build.gradle
docker-compose.yml
docker/api/Dockerfile
src/main/java/com/example/meettify/MeettifyApplication.java
src/main/java/com/example/meettify/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/meettify/config/s3/FileDTOFactory.java
src/main/java/com/example/meettify/config/s3/S3Config.java
src/main/java/com/example/meettify/config/s3/S3ImageUploadService.java

[Feat] S3 이미지 올리기 기능 구현

---

src/main/java/com/example/meettify/controller/MeetBoard/MeetBoardController.java
src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/dto/meet/MeetDetailDTO.java
src/main/java/com/example/meettify/dto/meet/MeetDetailInfoResponseDTO.java
src/main/java/com/example/meettify/dto/meet/MeetRole.java
src/main/java/com/example/meettify/dto/meet/MeetSummaryDTO.java
src/main/java/com/example/meettify/dto/meet/MeetUpdateServiceDTO.java
src/main/java/com/example/meettify/dto/meet/UpdateMeetDTO.java
src/main/java/com/example/meettify/dto/meetBoard/MeetBoardDetailsResponseDTO.java
src/main/java/com/example/meettify/dto/meetBoard/MeetBoardSummaryDTO.java
src/main/java/com/example/meettify/entity/Category.java
src/main/java/com/example/meettify/entity/Meet/MeetBoardEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetBoardImageEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetImageEntity.java
src/main/java/com/example/meettify/entity/Meet/MeetMemberEntity.java
src/main/java/com/example/meettify/exception/meet/MeetException.java
src/main/java/com/example/meettify/exception/meetBoard/MeetBoardException.java
src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
src/main/java/com/example/meettify/repository/meet/MeetRepository.java
src/main/java/com/example/meettify/repository/meetBoard/MeetBoardImageRepository.java
src/main/java/com/example/meettify/repository/meetBoard/MeetBoardRepository.java
src/main/java/com/example/meettify/service/meet/MeetService.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

모임 리스트 보기
모임 상세 정보 보기 
모임 만들기 
모임 삭제 
모임 수정 권한 체크하기 
모임에 대한 수정 진행하기 
회원이 특정 모임에 가입 신청하기 
close #42  #40  #39  #32

[Feat] 모임 관련 기능 추가

---

src/main/java/com/example/meettify/dto/meetBoard/MeetBoardSummaryDTO.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Feat] 모임 게시판 요약 정보 제공 기능 구현

---

src/main/java/com/example/meettify/dto/meet/MeetServiceDTO.java
src/main/java/com/example/meettify/dto/meet/RequestMeetDTO.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Modify] 배열로 받는 부분 List로 수정

---

docker-compose.yml
src/main/java/com/example/meettify/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/meettify/config/jwt/JwtProvider.java
src/main/java/com/example/meettify/config/modelMapper/RootConfig.java
src/main/java/com/example/meettify/config/oauth/OAuth2SuccessHandler.java
src/main/java/com/example/meettify/config/oauth/PrincipalOAuthUserService.java
src/main/java/com/example/meettify/config/security/SecurityConfig.java
src/main/java/com/example/meettify/config/swagger/SwaggerConfig.java
src/main/java/com/example/meettify/controller/member/MemberController.java
src/main/java/com/example/meettify/controller/member/MemberControllerDocs.java
src/main/java/com/example/meettify/dto/jwt/TokenDTO.java
src/main/java/com/example/meettify/dto/member/MemberServiceDTO.java
src/main/java/com/example/meettify/dto/member/RequestMemberDTO.java
src/main/java/com/example/meettify/dto/member/ResponseMemberDTO.java
src/main/java/com/example/meettify/dto/member/UpdateMemberServiceDTO.java
src/main/java/com/example/meettify/entity/jwt/TokenEntity.java
src/main/java/com/example/meettify/entity/meet/MeetMemberEntity.java
src/main/java/com/example/meettify/entity/member/MemberEntity.java
src/main/java/com/example/meettify/service/member/MemberService.java
src/main/java/com/example/meettify/service/member/MemberServiceImpl.java
src/main/resources/application-prod.yml

[Modify] 도메인 모델 패턴으로 수정

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/dto/meet/MeetServiceDTO.java
src/main/java/com/example/meettify/dto/meet/ResponseMeetDTO.java
src/main/java/com/example/meettify/dto/meetBoard/MeetBoardServiceDTO.java
src/main/java/com/example/meettify/dto/meetBoard/RequestMeetBoardDTO.java
src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardDTO.java
src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardDetailsDTO.java
src/main/java/com/example/meettify/entity/meet/MeetImageEntity.java
src/main/java/com/example/meettify/entity/meetBoard/MeetBoardEntity.java
src/main/java/com/example/meettify/entity/meetBoard/MeetBoardImageEntity.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

[Feat] 모임 게시글 작성 기능

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/entity/meet/MeetEntity.java
src/main/java/com/example/meettify/entity/meetBoard/MeetBoardEntity.java
src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

[Feat] 모임 게시글 삭제하기

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/dto/meetBoard/UpdateMeetBoardServiceDTO.java
src/main/java/com/example/meettify/dto/meetBoard/UpdateRequestMeetBoardDTO.java
src/main/java/com/example/meettify/entity/meetBoard/MeetBoardEntity.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

[Feat] 모임 게시글 수정하기

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/dto/meetBoard/MeetBoardSummaryDTO.java
src/main/java/com/example/meettify/repository/meetBoard/MeetBoardRepository.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

[Feat] 모임 게시글 페이징 기능 구현

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/dto/meet/MeetRole.java

모임 권한 정보를 가져오는 API 기능 구현 
close  #126

[Feat] 모임 권한 정보 가져오는 기능 구현

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/dto/meet/MeetRole.java
src/main/java/com/example/meettify/dto/meet/ResponseMeetMemberDTO.java
src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
src/main/java/com/example/meettify/service/meet/MeetService.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Feat] 모임 회원 명단 보여주기

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/dto/meet/MeetRole.java
src/main/java/com/example/meettify/entity/meet/MeetMemberEntity.java
src/main/java/com/example/meettify/service/meet/MeetService.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

- 모임 Role 추가 
- 권한 오류 FORBIDDEN으로 처리 
close #128 
close #129

[Feat] 모임 Role 전환시키는 기능 구현

---

src/main/java/com/example/meettify/controller/member/MemberController.java
src/main/java/com/example/meettify/controller/member/MemberControllerDocs.java
src/main/java/com/example/meettify/dto/member/role/UserRole.java
src/main/java/com/example/meettify/service/member/MemberService.java
src/main/java/com/example/meettify/service/member/MemberServiceImpl.java

[Feat] 회원 조회기능 구현

---

src/main/java/com/example/meettify/config/security/SecurityConfig.java
src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
src/main/java/com/example/meettify/dto/meet/MeetServiceDTO.java
src/main/java/com/example/meettify/dto/meet/ResponseMeetDTO.java
src/main/java/com/example/meettify/dto/meet/UpdateRoleRequestDTO.java
src/main/java/com/example/meettify/entity/meet/MeetEntity.java
src/main/java/com/example/meettify/entity/meet/MeetMemberEntity.java
src/main/java/com/example/meettify/repository/meet/MeetRepository.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[FIx] 모임 API 에러 해결

---

src/main/java/com/example/meettify/entity/meetBoard/CommentEntity.java

[Feat] 모임 게시판의 댓글 엔티티 구현

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/dto/meetBoard/RequestMeetBoardCommentDTO.java
src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardCommentDTO.java
src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardDetailsDTO.java
src/main/java/com/example/meettify/dto/meetBoard/UpdateMeetBoardServiceDTO.java
src/main/java/com/example/meettify/entity/meetBoard/MeetBoardEntity.java
src/main/java/com/example/meettify/entity/meetBoard/MeetBoardImageEntity.java
src/main/java/com/example/meettify/repository/meetBoard/CommentRepository.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

[Feat] 모임 게시판 대댓글 읽기 기능 구현

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardControllerDocs.java
src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardDTO.java
src/main/java/com/example/meettify/dto/meetBoard/UpdateRequestMeetBoardDTO.java
src/main/java/com/example/meettify/repository/meetBoard/MeetBoardRepository.java

[Fix] 모임 게시판 API 에러 해결

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

[Docs] 모임 관련 주석 다듬기

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentController.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentControllerDocs.java
src/main/java/com/example/meettify/dto/meetBoard/MeetBoardCommentServiceDTO.java
src/main/java/com/example/meettify/dto/meetBoard/RequestMeetBoardCommentDTO.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentServiceImpl.java

[Feat] 모임 게시판 대댓글 삭제 기능 구현

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentController.java
src/main/java/com/example/meettify/exception/meetBoardComment/MeetBoardCommentException.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentServiceImpl.java

MeetException -> MeetBoardCommentException

[Refactor] 모임 게시판 대댓글 예외 처리 수정

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
src/main/java/com/example/meettify/dto/meet/MeetSummaryDTO.java
src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
src/main/java/com/example/meettify/repository/meet/MeetRepository.java
src/main/java/com/example/meettify/service/meet/MeetService.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

기존 모임 리스트 정보 제공해주기에서 추가로 가입여부 정보 제공해준다. 
close #182

[Feat] 모임 리스트에서 가입 여부 정보 제공

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/dto/meet/MeetDetailInfoResponseDTO.java
src/main/java/com/example/meettify/dto/meet/MeetPermissionDTO.java
src/main/java/com/example/meettify/service/meet/MeetService.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Feat] 모임 상세에 권한 정보 전달 기능 추가

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/dto/meetBoard/MeetBoardCommentPermissionDTO.java
src/main/java/com/example/meettify/dto/meetBoard/MeetBoardDetailsDTO.java
src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardCommentDTO.java
src/main/java/com/example/meettify/repository/meetBoard/MeetBoardCommentRepository.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentServiceImpl.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

모임 게시판 댓글 상세에 권한 정보 전달 기능

---

src/main/java/com/example/meettify/dto/meet/MeetRole.java

[Feat] 모임 권한 enum에 Swagger 설명 추가

---

src/main/java/com/example/meettify/controller/meet/MeetController.java

[Fix] 모임 정보 가져오기 API 오류 수정

---

src/main/java/com/example/meettify/controller/item/ItemController.java
src/main/java/com/example/meettify/controller/item/ItemControllerDocs.java
src/main/java/com/example/meettify/dto/item/ItemSearchCondition.java
src/main/java/com/example/meettify/repository/item/CustomItemRepository.java
src/main/java/com/example/meettify/repository/item/ItemRepository.java
src/main/java/com/example/meettify/repository/item/ItemRepositoryImpl.java
src/main/java/com/example/meettify/service/item/ItemService.java
src/main/java/com/example/meettify/service/item/ItemServiceImpl.java

- 상품 조회 기능
close #221 
- 상품 삭제 기능 
close #8 
- 상품 페이징 기능 구현
close #227

[Feat] 상품 기능 구현

---

build.gradle
src/main/java/com/example/meettify/dto/meet/category/Category.java

SPORTS - 스포츠
TRAVEL - 여행 (여행 + 캠핑 )
MUSIC - 음악
ART - 예술 (상품으로 미술 물품 판매)
READING - 독서 (서적 및 독서 용품, 책갈피, 북라이트 판매)
HEALTH - 건강 (건강 관련 상품 판매)
FASHION & BEAUTY - 패션/뷰티
PET LOVERS - 반려동물 (애견 용품)
close #229

[Feat] Category enum 클래스 구현

---

src/main/java/com/example/meettify/controller/community/CommunityController.java
src/main/java/com/example/meettify/controller/community/CommunityControllerDocs.java
src/main/java/com/example/meettify/dto/board/CreateBoardDTO.java
src/main/java/com/example/meettify/dto/board/CreateServiceDTO.java
src/main/java/com/example/meettify/dto/board/ResponseBoardDTO.java
src/main/java/com/example/meettify/dto/board/ResponseBoardImgDTO.java
src/main/java/com/example/meettify/dto/board/UpdateBoardDTO.java
src/main/java/com/example/meettify/dto/board/UpdateServiceDTO.java
src/main/java/com/example/meettify/entity/community/CommunityEntity.java
src/main/java/com/example/meettify/entity/community/CommunityImgEntity.java
src/main/java/com/example/meettify/repository/community/CommunityRepository.java
src/main/java/com/example/meettify/service/community/CommunityService.java
src/main/java/com/example/meettify/service/community/CommunityServiceImpl.java

- 커뮤니티 게시글 생성
close #222 
- 커뮤니티 게시글 조회
close #223 
- 커뮤니티 게시글 수정
close #224

[Feat] 커뮤니티 기능 구현

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/dto/meet/MeetDetailDTO.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Fix] 모임 상세 기능 이미지 로직 에러 수정

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardControllerDocs.java
src/main/java/com/example/meettify/dto/meetBoard/MeetBoardServiceDTO.java
src/main/java/com/example/meettify/dto/meetBoard/RequestMeetBoardDTO.java

[Fix] 모임 게시판 이미지 등록 로직 에러 수정

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
src/main/java/com/example/meettify/dto/meet/MeetSearchCondition.java
src/main/java/com/example/meettify/dto/meet/MeetSummaryDTO.java
src/main/java/com/example/meettify/repository/meet/CustomMeetRepository.java
src/main/java/com/example/meettify/repository/meet/MeetRepository.java
src/main/java/com/example/meettify/repository/meet/MeetRepositoryImpl.java
src/main/java/com/example/meettify/service/meet/MeetService.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Modify] 모임 리스트 기능 검색기능으로 변경

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
src/main/java/com/example/meettify/dto/meet/ResponseMeetDTO.java
src/main/java/com/example/meettify/dto/meet/UpdateMeetDTO.java
src/main/java/com/example/meettify/service/meet/MeetService.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Modify] 모임 변경 기능 모임 이미지 S3에서 삭제 되도록 수정

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

[Modify] 모임 게시판 삭제 기능 이미지 S3에서 삭제 되도록 수정

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardControllerDocs.java
src/main/java/com/example/meettify/dto/meetBoard/UpdateMeetBoardServiceDTO.java
src/main/java/com/example/meettify/dto/meetBoard/UpdateRequestMeetBoardDTO.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java

[Modify] 모임 게시판 변경시 모임 이미지 S3에서 삭제 되도록 수정

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
src/main/java/com/example/meettify/dto/meet/MyMeetResponseDTO.java
src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
src/main/java/com/example/meettify/service/meet/MeetService.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Feat] 가입 모임 리스트 보여주기 구현

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/dto/meet/MyMeetResponseDTO.java
src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Modify] 가입 모임 리스트에 권한 정보 추가

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
src/main/java/com/example/meettify/dto/meet/MeetRole.java
src/main/java/com/example/meettify/dto/meet/MyMeetResponseDTO.java

[Feat] 모임 탈퇴하기 기능 구현

---

src/main/java/com/example/meettify/controller/search/SearchController.java
src/main/java/com/example/meettify/controller/search/SearchControllerDocs.java
src/main/java/com/example/meettify/dto/meet/MeetSummaryDTO.java
src/main/java/com/example/meettify/dto/search/SearchCondition.java
src/main/java/com/example/meettify/dto/search/SearchEntityDTO.java
src/main/java/com/example/meettify/dto/search/SearchResponseDTO.java
src/main/java/com/example/meettify/repository/search/SearchCustomRepositoryImpl.java
src/main/java/com/example/meettify/service/search/SearchService.java
src/main/java/com/example/meettify/service/search/SearchServiceImpl.java

[Feat] 전체 검색기능 구현

---

src/main/java/com/example/meettify/entity/meetBoard/MeetBoardCommentEntity.java

[Fix] 모임 게시글 댓글 @Builder 경고

---

src/main/java/com/example/meettify/repository/search/SearchCustomRepositoryImpl.java

[Fix] QCommunityEntity 필드 오류 수정

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentControllerDocs.java

[Modify] 모임 게시판 댓글 API Swagger문서 수정

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Fix] 모임 디테일 에러 수정

---

src/main/java/com/example/meettify/controller/meet/MeetController.java
src/main/java/com/example/meettify/dto/meet/UpdateMeetDTO.java
src/main/java/com/example/meettify/dto/meet/UpdateMeetServiceDTO.java

[Modify] 모임 수정 API 명세서 수정

---

src/main/java/com/example/meettify/config/security/SecurityConfig.java
src/main/java/com/example/meettify/controller/meet/MeetController.java

[Modify] 모임관련 Security 접근 권한 수정

---

src/main/java/com/example/meettify/config/security/SecurityConfig.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentController.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentControllerDocs.java
src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java

[Modify] 모임 게시판관련 Security 접근 권한 수정

---

src/main/java/com/example/meettify/config/security/SecurityConfig.java
src/main/java/com/example/meettify/controller/search/SearchController.java

[Modify] 검색관련 Security 접근 권한 수정

---

src/main/java/com/example/meettify/entity/meet/MeetEntity.java

[Fix] 모임 변경 에러 수정

---

src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java

[Modify] 모임 인원 수에 맞게 인원 받도록 수정

---

src/main/java/com/example/meettify/controller/community/CommunityController.java
src/main/java/com/example/meettify/dto/board/ResponseCommunityDTO.java
src/main/java/com/example/meettify/dto/meet/ResponseMeetMemberDTO.java
src/main/java/com/example/meettify/dto/search/SearchResponseDTO.java
src/main/java/com/example/meettify/service/community/CommunityService.java
src/main/java/com/example/meettify/service/community/CommunityServiceImpl.java
src/main/java/com/example/meettify/service/notice/NoticeServiceImpl.java
src/main/java/com/example/meettify/service/search/SearchServiceImpl.java

[Fix] 모임 멤버 오류 수정 

---

src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentController.java
src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardCommentDTO.java
src/main/java/com/example/meettify/dto/meetBoard/UpdateMeetBoardCommentDTO.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentService.java
src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentServiceImpl.java

[Feat] 모임 게시판 대댓글 수정 기능 구현

---

src/main/java/com/example/meettify/controller/meet/MeetController.java

[Fix] 모임 리스트 에러 수정

---

src/main/java/com/example/meettify/controller/cart/CartController.java
src/main/java/com/example/meettify/controller/cart/CartControllerDocs.java
src/main/java/com/example/meettify/dto/cart/ResponseCartDTO.java
src/main/java/com/example/meettify/dto/cart/ResponseCartItemDTO.java
src/main/java/com/example/meettify/repository/cart/CartItemRepository.java
src/main/java/com/example/meettify/repository/cart/CartRepository.java
src/main/java/com/example/meettify/service/cart/CartService.java
src/main/java/com/example/meettify/service/cart/CartServiceImpl.java

[Feat] 장바구니 조회 기능

---

build.gradle
src/main/java/com/example/meettify/config/metric/TimeTrace.java
src/main/java/com/example/meettify/config/metric/TimeTraceAspect.java

[Feat] Time metric 기능 구현

---

src/main/java/com/example/meettify/controller/question/QuestionController.java
src/main/java/com/example/meettify/controller/question/QuestionControllerDocs.java
src/main/java/com/example/meettify/dto/board/ResponseCommunityDTO.java
src/main/java/com/example/meettify/dto/board/UpdateQuestionDTO.java
src/main/java/com/example/meettify/dto/question/ReplyStatus.java
src/main/java/com/example/meettify/dto/question/ResponseQuestionDTO.java
src/main/java/com/example/meettify/entity/question/QuestionEntity.java
src/main/java/com/example/meettify/repository/question/QuestionRepository.java
src/main/java/com/example/meettify/service/question/QuestionService.java
src/main/java/com/example/meettify/service/question/QuestionServiceImpl.java
src/main/resources/application-prod.yml

- 문의글 등록
close #362 
- 문의글 수정
close #363

[Feat] 문의글 기능 구현

---

src/main/java/com/example/meettify/config/slack/SlackUtil.java
src/main/java/com/example/meettify/controller/comment/CommentController.java
src/main/java/com/example/meettify/exception/GlobalExceptionAdvice.java

[Fix] 오류 해결

---

docker-compose.yml
src/main/java/com/example/meettify/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/meettify/config/jwt/JwtProvider.java
src/main/java/com/example/meettify/config/redis/RedisRepositoryConfig.java
src/main/java/com/example/meettify/controller/jwt/TokenController.java
src/main/java/com/example/meettify/controller/jwt/TokenControllerDocs.java
src/main/java/com/example/meettify/entity/jwt/TokenEntity.java
src/main/java/com/example/meettify/repository/jwt/TokenRepository.java
src/main/java/com/example/meettify/service/jwt/TokenService.java
src/main/java/com/example/meettify/service/jwt/TokenServiceImpl.java
src/main/resources/application-prod.yml

기존 RDS에 저장하던 토큰을 레디스에 저장으로 수정
close #368

[Modify] 토큰을 RDS에서 Redis 저장 수정

---

src/main/java/com/example/meettify/controller/meet/MeetController.java

[Modify] 모임 리스트 페이지 기본값 수정

---

src/main/java/com/example/meettify/service/community/CommunityServiceImpl.java
src/main/java/com/example/meettify/service/community/RedisService.java

[Modify] 커뮤니티 삭제로직 수정

---

src/main/java/com/example/meettify/config/redis/RedisConfig.java
src/main/java/com/example/meettify/controller/community/CommunityController.java
src/main/java/com/example/meettify/controller/community/CommunityControllerDocs.java
src/main/java/com/example/meettify/repository/community/CommunityRepository.java
src/main/java/com/example/meettify/service/community/CommunityService.java
src/main/java/com/example/meettify/service/community/CommunityServiceImpl.java

[Feat] 마이페이지 커뮤니티 리스트 기능 구현

---

src/main/java/com/example/meettify/controller/community/CommunityController.java
src/main/java/com/example/meettify/controller/community/CommunityControllerDocs.java
src/main/java/com/example/meettify/controller/question/QuestionController.java
src/main/java/com/example/meettify/controller/question/QuestionControllerDocs.java
src/main/java/com/example/meettify/repository/community/CommunityRepository.java
src/main/java/com/example/meettify/repository/question/QuestionRepository.java
src/main/java/com/example/meettify/service/community/CommunityServiceImpl.java
src/main/java/com/example/meettify/service/order/OrderService.java
src/main/java/com/example/meettify/service/question/QuestionService.java
src/main/java/com/example/meettify/service/question/QuestionServiceImpl.java

[Feat] 마이페이지 문의 내역 기능 구현

---

src/main/java/com/example/meettify/controller/order/OrderController.java
src/main/java/com/example/meettify/controller/order/OrderControllerDocs.java
src/main/java/com/example/meettify/controller/question/QuestionController.java
src/main/java/com/example/meettify/controller/question/QuestionControllerDocs.java
src/main/java/com/example/meettify/dto/member/AddressDTO.java
src/main/java/com/example/meettify/dto/order/ResponseOrderDTO.java
src/main/java/com/example/meettify/repository/order/OrderRepository.java
src/main/java/com/example/meettify/service/community/RedisService.java
src/main/java/com/example/meettify/service/order/OrderService.java
src/main/java/com/example/meettify/service/order/OrderServiceImpl.java

[Feat] 마이페이지 내 주문 내역 보기

---

src/main/java/com/example/meettify/controller/item/ItemController.java
src/main/java/com/example/meettify/controller/item/ItemControllerDocs.java
src/main/java/com/example/meettify/controller/search/SearchController.java
src/main/java/com/example/meettify/repository/item/CustomItemRepository.java
src/main/java/com/example/meettify/repository/item/ItemRepositoryImpl.java
src/main/java/com/example/meettify/service/community/CommunityServiceImpl.java
src/main/java/com/example/meettify/service/community/RedisCommunityService.java
src/main/java/com/example/meettify/service/community/ScheduledTasks.java
src/main/java/com/example/meettify/service/item/ItemService.java
src/main/java/com/example/meettify/service/item/ItemServiceImpl.java
src/main/java/com/example/meettify/service/search/RedisSearchLogService.java
src/main/java/com/example/meettify/service/search/SearchServiceImpl.java

[Feat] 상품 추천 기능 구현

---

src/main/java/com/example/meettify/config/security/SecurityConfig.java
src/main/java/com/example/meettify/controller/item/ItemController.java
src/main/java/com/example/meettify/controller/item/ItemControllerDocs.java
src/main/java/com/example/meettify/entity/item/ItemEntity.java
src/main/java/com/example/meettify/repository/item/CustomItemRepository.java
src/main/java/com/example/meettify/repository/item/ItemRepository.java
src/main/java/com/example/meettify/repository/item/ItemRepositoryImpl.java
src/main/java/com/example/meettify/repository/member/MemberRepository.java
src/main/java/com/example/meettify/service/item/ItemService.java
src/main/java/com/example/meettify/service/item/ItemServiceImpl.java
src/main/java/com/example/meettify/service/notification/NotificationService.java

[Feat] 대기중인 상품 리스트 기능 구현

---

src/main/java/com/example/meettify/config/websocket/StompHandler.java
src/main/java/com/example/meettify/config/websocket/WebSocketConfig.java
src/main/java/com/example/meettify/controller/chat/ChatRoomController.java
src/main/java/com/example/meettify/controller/chat/ChatRoomControllerDocs.java
src/main/java/com/example/meettify/controller/order/OrderController.java
src/main/java/com/example/meettify/controller/order/OrderControllerDocs.java
src/main/java/com/example/meettify/dto/chat/ChatMemberDTO.java
src/main/java/com/example/meettify/dto/chat/RequestAccessEmailDTO.java
src/main/java/com/example/meettify/dto/order/OrderRequestWrapperDTO.java
src/main/java/com/example/meettify/service/chat/ChatService.java
src/main/java/com/example/meettify/service/chat/ChatServiceImpl.java

close #107 
close #108 
close #440
close #441

[Feat] 채팅 기능 구현

---

.github/workflows/action.yml
src/main/java/com/example/meettify/controller/item/ItemController.java
src/main/java/com/example/meettify/entity/order/OrderItemEntity.java
src/main/java/com/example/meettify/entity/order/OrderItemSnapshot.java
src/main/java/com/example/meettify/exception/GlobalExceptionAdvice.java

CI/CD에 맞게 수정
**추가점**
- 취약점 스캔
- 보안 리포트

Git Action 설정 수정
